library(shiny)
library(magrittr)
library(DT)

source(file.path(pf, "modules/create_selectors.R"))
source(file.path(pf, "modules/ensureListStructure.R"))
source(file.path(pf, "modules/get_scaling_factor.R"))
source(file.path(pf, "modules/wrap_text.R"))
source(file.path(pf, "modules/remind_dictionary.R"))
source(file.path(pf, "modules/PlotServer.R"))
source(file.path(pf, "modules/dataTableServer.R"))
source(file.path(pf, "modules/downloadModule.R"))
source(file.path(pf, "modules/dataFilter.R"))
source(file.path(pf, "modules/combine_multiple_columns.R"))
source(file.path(pf, "modules/createViz.R"))
