#define data source
data.file: "data/topo_warehouse_meta_v1_2.csv"
data.wrangler: "R/data_prep_topo.R" 

#define plot type 
gopts: "area"
 
#define main plot variables 
x_var: "year"
x_var_lab: "Year"
y_var: "value"
y_var_lab: "Value"
color_var: "d4_concept_lab"
color_var_lab: "Concept"
color_style: "nationalparkcolors::Badlands"

#Define main selectors 
selector_info:
  GEO_long:
    label: "Country"
    selected: "United States"
  legend:
    label: "Source"
    selected:
      - "World Inequality Database - Balance Sheet"
      - "Credit Suisse Global Wealth Report"
      - "Luxembourg Wealth Study Database - Balance Sheet"
      - "Federal Reserve Board B.101.H - Balance Sheet"
    multiple: true
  xrate_lab: 
    label: "Currency"
    selected: "Euro (2023 prices)"
  pop_lab: 
    label: "Unit"
    selected: "Per capita"
  d2_sector_lab:
    label: "Sector"
    selected: "Households"
  d4_concept_lab:
    label: "Asset or Debt type"
    type: "checkbox"
    selected: 
      - "Debt" 
      - "Housing & Land"
      - "Financial Assets & Fixed Capital of Personal Businesses"
      
#facets 
facet_var: "legend"
facet_var_lab: "Source"

#Additional Variable Layer options
extra_layer:
   values: "Net Wealth"
   type: "line" 

#define the columns of the data table widget 
dt.cols:
  GEO: "Country code"
  year: "Year"
  GEO_long: "Country"
  d4_concept_lab: "Asset or Debt type"
  d2_sector_lab: "Sector"
  value: "Value"
  legend: "Source"
  metadata: "Description"

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  d4_concept_lab: "Wealth type:"
  value: "Value:"
  legend: "Source:"
 
#other options 
download.button: True
hide.selectors: False
listen: False
table.display: True
hide.legend: False
plot_height: 700
