#define data source
data.file: "data/eigt_ft_wide.qs"
data.wrangler: "custom_code/data_prep_eigt_ft.R"
keep.col:
  - "d2_label"
  - "exempt"

value_transform:
  type: "currency_columns"
  bundle.file: "data/currency_conversion_bundle.qs"
  currency_selector: "xrate_lab"
  columns:
    - "adjlbo"
  scale_divisor: 1000000

#define graph options 
gopts: "step"
plot_height: 700
overlap_offset:
  enabled: true
  amount: 0.003
  axis: "y"
  mode: "group_index"

download.button: True
hide.legend: False
hide.selectors: False
listen: False 
 
#define main plot variables 
axis_vars:
  x_axis:
    var: "adjlbo"
    label: "Bracket's lower bound (millions, selected currency)"
    breaks: 10
  y_axis:
    var: "adjmrt"
    label: "Marginal tax rate"

#define colors 
color:  
  var: "year" 
  label: "Year"
  style: "dichromat::DarkRedtoBlue_12"
  group:
    - "year"
    - "tax_type_view"
    - "kinship"

#Define main selector 
fixed_selectors:
  GEO_long:
    label: "Country"
    selected:
      - "Italy"
  tax_type_view:
    label: "Tax type"
    selected: "Inheritance or estate tax"
    choices:
      - "Inheritance or estate tax"
      - "Gift tax"
      - "Inheritance tax"
      - "Estate tax"
  xrate_lab:
    label: "Currency"
    selected: "USD (2023 prices)"
      
loose_selectors:
  kinship:
    label: "Kinship"
    type: "very reactive selector"
    selected: "Children"
  year:
    label: "Years"
    type: "very reactive checkbox"
    select: "spaced"


#define the columns of the data table widget 
dt.cols: 
  GEO_long: "Country"
  GEO: "Country code"
  year: "Year"
  tax_type: "Source tax type"
  kinship: "Kinship"
  d5_code: "Bracket"
  adjmrt: "Marginal tax rate"
  xrate_lab: "Currency"
  adjlbo: "Lower bound (millions, selected currency)"

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  tax_type: "Source tax type:"
  kinship: "Kinship:"
  adjmrt: "Marginal tax rate"
  xrate_lab: "Currency:"
  adjlbo: "Lower bound (millions):"

#other options 
table.display: True
