#define data source
data.file: "data/eigt_warehouse_meta_v1_2.csv"
data.wrangler: "custom_code/data_prep_eigt2.R" 

#define plot type 
gopts: "line"
 
#define main plot variables 
x_var: "year"
x_var_lab: "Year"
xnum_breaks: 10  
y_var: "value"
y_var_lab: "Value"
color_var: "GEO_long"
color_var_lab: "Country"
color_style: "dichromat::DarkRedtoBlue_12"
groupvars: 
  - "GEO_long"
  - "d2_sector_lab"

#Define main selector 
selector_info:
  GEO_long:
    label: "Country"
    selected:
      - "Italy"
      - "France" 
      - "United States"
      - "Canada"
      - "Sweden"
    multiple: true   
  d4_concept_lab: 
    label: "Tax Features"
    selected: "Total Revenue from Tax as % of Total Tax Revenue"
    
loose_selectors: 
  d2_sector_lab: 
    label: "Tax type"
    type: "checkbox"
  
#define the columns of the data table widget 
dt.cols: 
  GEO_long: "Country code"
  year: "Year"
  d4_concept_lab: "Variable"
  value: "Value"
  d2_sector_lab: "Tax type"
  

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  value: "Value:"  
  d4_concept_lab: "Concept:"
  d2_sector_lab: "Tax type:"

#other options 
download.button: True
hide.selectors: False
listen: False
table.display: True
hide.legend: False
plot_height: 700
