#define data source
data.file: "data/eigt_wide.qs"

#define graph options 
gopts: "step"
plot_height: 700

download.button: True
hide.legend: False
hide.selectors: False
listen: False 
 
#define main plot variables 
axis_vars:
  x_axis:
    var: "adjlbo"
    label: "Bracket's Lower bound (USD Million, inflation adjusted)"
    breaks: 10
  y_axis:
    var: "adjmrt"
    label: "Marginal tax rate"

#define colors 
color:  
  var: "year" 
  label: "Year"
  style: "dichromat::DarkRedtoBlue_12"
  group:
    - "year"
    - "d2_label"

#Define main selector 
fixed_selectors:
  GEO_long:
    label: "Country"
    selected:
      - "Italy"
      
loose_selectors: 
   year:
    label: "Years"
    type: "checkbox"
    select: "spaced"
   d2_label:
    label: "Tax type"
    selected: "Estate Tax for Everybody"
    type: "checkbox"   

#define the columns of the data table widget 
dt.cols: 
  GEO_long: "Country code"
  year: "Year"
  d2_label: "Tax type"
  d5_code: "Bracket"
  adjmrt: "Marginal tax rate"
  adjlbo: "Lower bound in adjusted USD Millions"

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  d2_label: "Tax type:"
  adjmrt: "Marginal tax rate"
  adjlbo: "Lower bound in adjusted USD Millions"

#other options 
table.display: True
