#define data source
data.file: "data/topo_warehouse_meta_v1_2.csv"
data.wrangler: "R/data_prep_topo_debtplus.R" 

#define plot type 
gopts: 
 - "line"
 
#define main plot variables 
x_var: "year"
x_var_lab: "Year"
y_var: "value"
y_var_lab: "Value"
color_var: "GEO_long"
color_var_lab: "Country"
color_style: "MoMAColors::Abbott"
groupvars:
  - "GEO_long"
  - "legend"

#Define main selectors 
selector_info:
  GEO_long:
    label: "Country"
    selected: 
      - "all"
      - "United States"
      - "Germany" 
      - "Italy"
    multiple: true   
  xrate_lab: 
    label: "Currency"
    selected: "Euro (2023 prices)"
  pop_lab: 
    label: "Unit"
    selected: "Per capita"
  d2_sector_lab:
    label: "Sector"
    selected: "Households & NPISH"
  d4_concept_lab:
    label: "Asset or Debt type"
    selected: "Debt"  
    
#Define reactive or 'loose' selectors (react to changes in main selectors)
loose_selectors:
  legend:
    label: "Source"
    type: "checkbox"

#define the columns of the data table widget 
dt.cols:
  GEO: "Country code"
  year: "Year"
  GEO_long: "Country"
  d4_concept_lab: "Asset or Debt type"
  d2_sector_lab: "Sector"
  value: "Value"
  legend: "Source"
  metadata: "Description"

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  value: "Value:"
  legend: "Source:"
 
#other options 
download.button: True
hide.selectors: False
listen: False
table.display: True
hide.legend: False
plot_height: 700
