#define data source
data.file: "data/eigt_wide_viz.csv"
data.wrangler: "custom_code/data_prep_eigt.R" 

#define plot type 
gopts: "step"
 
#define main plot variables 
axis_vars: 
  x_axis: 
    var: "adjlbo"
    label: "Bracket's Lower bound (USD Million, inflation adjusted)"
    breaks: 10 
  y_axis: 
    var: "adjmrt"
    label: "Marginal tax rate"
    
color: 
  var: "Country"
  label: "Country" 
  style: "dichromat::DarkRedtoBlue_12"
  group:
    - "year"
    - "tax"

#Define main selector 
fixed_selectors:
  year: 
    label: "Year"
    selected: 2008
  Country:
    label: "Country"
    selected:
      - "Italy"
      - "France" 
      - "Germany"
    multiple: true   
      
loose_selectors: 
   tax:
    label: "Tax type"
    selected: "Estate Tax"
    type: "checkbox"

#define the columns of the data table widget 
dt.cols: 
  GEO: "Country code"
  year: "Year"
  tax: "Tax type"
  bracket: "Bracket"
  currency: "Currency"
  adjmrt: "Marginal tax rate"
  adjlbo: "Lower bound in adjusted USD Millions"

#define the information shown in the tooltip
tooltip_vars:
  GEO: "Country:"
  year: "Year:"
  tax: "Tax type:"
  currency: "Currency"
  adjmrt: "Marginal tax rate"
  adjlbo: "Lower bound in adjusted USD Millions"

#other options 
download.button: True
hide.selectors: False
listen: False
table.display: True
hide.legend: False
plot_height: 700
