#define data source
data.file: "data/topo_ready_dp.qs"
meta.file: "data/topo_meta.qs"
meta.loc: "tab"

#define plot type 
gopts: 
 - "line"
 
#define main plot variables 
axis_vars: 
  x_axis: 
    var: "year" 
    label: "Year"
  y_axis: 
    var: "value" 
    label: "Value" 

color:
  var: "legend"
  label: "Source"
  style: "PNWColors::Bay"
  group:
    - "d2_sector_lab"
    - "legend"

#Define main selectors 
fixed_selectors:
  GEO_long:
    label: "Country"
    selected: "United States"
  xrate_lab: 
    label: "Currency"
    selected: "Euro (2023 prices)"
  pop_lab: 
    label: "Unit"
    selected: "Per capita"
  d2_sector_lab:
    label: "Sector"
    selected: 
      - "Households & NPISH"
      - "Households"
    multiple: true  
  d4_concept_lab:
    label: "Asset or Debt type"
    selected: "Debt"  
    
#Define reactive or 'loose' selectors (react to changes in main selectors)
loose_selectors:
  legend:
    label: "Source"
    type: "checkbox"

#define the columns of the data table widget 
dt.cols:
  GEO: "Country code"
  year: "Year"
  GEO_long: "Country"
  d4_concept_lab: "Asset or Debt type"
  d2_sector_lab: "Sector"
  value: "Value"
  legend: "Source"
  metadata: "Description"

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  value: "Value:"
  d4_concept_lab: "Wealth type:"
  legend: "Source:"
 
#other options 
download.button: True
hide.selectors: False
listen: False
table.display: True
hide.legend: False
plot_height: 700
