#define data source
data.file: "data/inhe_warehouse_meta_v2.csv"
data.wrangler: "custom_code/dictionary_loader_inhe.R"

#define plot type 
gopts: 
 - "line"
 - "point"
plot_height: 480
hide.selectors: True
hide.legend: True
download.button: False
listen: True

#combine columns into a string variable if needed 
new.cols: 
  con_sou_val:
    - "legend"
    - "d4_concept_lab"
    - "d5_dboard_specific_lab"
 
#define main plot variables 
axis_vars: 
  x_axis:
    var: "year"
    label: "Year"
    breaks: 10 
  y_axis:   
    var: "value" 

color:     
  var: "con_sou_val"
  label: "Source"
  style: "LaCroixColoR::Apricot"

#Define main selectors 
fixed_selectors:
  GEO_long:
    label: "Country"
    selected:
      - "United States"
  d3_vartype_lab:
     label: "Variable"
     selected: "Ratio" 

#define loose selectors 
loose_selectors:
   legend: 
    label: "Source"
    type: "checkbox"
   d4_concept_lab:
    label: "Concept" 
    type: "checkbox"
   d5_dboard_specific_lab:
    label: "Valutation"
    type: "checkbox"       
      

#define the columns of the data table widget 
dt.cols:
  GEO: "Country code"
  year: "Year"
  GEO_long: "Country"
  value: "Value"
  d4_concept_lab: "Concept"
  d5_dboard_specific_lab: "Valuation"
  legend: "Source"
  
table.display: False 

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  value: "Value:"
  legend: "Source"
  d4_concept_lab: "Concept"
  d5_dboard_specific_lab: "Valuation"  
  



