#define data source
data.file: "data/taxw_warehouse_meta_v2.csv"
data.wrangler: "custom_code/data_prep_eigt2.R" 
keep.col:
  - "GEO"
  - "d2_sector_lab"

#define plot type 
gopts: "line"
 
#define main plot variables 
axis_vars: 
  x_axis: 
    var: "year" 
    label: "Year" 
    breaks: 10 
  y_axis: 
    var: "value"
    label: "Value"

color: 
  var: "GEO_long"
  label: "Country"
  style: "dichromat::DarkRedtoBlue_12"
  group: 
    - "GEO_long"
    - "tax_category"

#Define main selector 
fixed_selectors:
  GEO_long:
    label: "Country"
    selected:
      - "Italy"
      - "France" 
      - "United States"
      - "Canada"
      - "Sweden"
    multiple: true   
  d4_concept_lab: 
    label: "Tax Features"
    selected: "Total Revenue from Tax as % of Total Tax Revenue"
    choices:
      - "Top Marginal Rate"
      - "Exemption Threshold"
      - "Total Revenue from Tax"
      - "Total Revenue from Tax as % of Total Tax Revenue"
      - "Total Revenue from Tax as % of Gross Domestic Product"
  xrate_lab:
    label: "Currency & Price Adjustment"
    selected: "Euro adjusting for inflation"
    choices:
      - "National Currency"
      - "National Currency adjusting for inflation"
      - "USD"
      - "USD adjusting for inflation"
      - "Euro"
      - "Euro adjusting for inflation"
      - "Yuan"
      - "Yuan adjusting for inflation"
      - "PPP USD"
      - "PPP Euro"
      - "PPP Yuan"
    
loose_selectors: 
  tax_category:
    label: "Tax category"
    type: "sticky selector"
    select: "first"
    selected: "Estate, inheritance and gift taxes (EIG)"
  
#define the columns of the data table widget 
dt.cols: 
  GEO_long: "Country"
  year: "Year"
  d4_concept_lab: "Variable"
  value: "Value"
  tax_category: "Tax category"
  xrate_lab: "Currency & price adjustment"
  

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  value: "Value:"  
  d4_concept_lab: "Concept:"
  tax_category: "Tax category:"
  xrate_lab: "Currency & price adjustment:"

download.cols:
  - "d2_sector_lab"
  - "tax_type"
  - "tax_type_view"
  - "kinship"
  - "revenue_tax_category"

#other options 
download.button: True
hide.selectors: False
listen: False
table.display: True
hide.legend: False
plot_height: 700
