#define data source
data.file: "data/eigt_wide.qs"
data.wrangler: "custom_code/data_prep_eigt_kf1_dual.R"

#define plot type
gopts: "dual_axis_line"

#define main plot variables
axis_vars:
  x_axis:
    var: "year"
    label: "Year"
    breaks: 10
  y_axis:
    var: "prorev"
    label: "Left Axis"
    choices: c("prorev", "revgdp")
    alt.names: c("EIG Tax % Total Tax Revenue", "EIG Tax % GDP")
  y2_axis:
    var: "toprat"
    label: "Right Axis"
    choices: c("toprat", "prorev", "revgdp")
    alt.names: c("Top Marginal Rate", "EIG Tax % Total Tax Revenue", "EIG Tax % GDP")

color:
  var: "GEO_long"
  label: "Country"
  style: "dichromat::DarkRedtoBlue_12"

#Define main selectors
fixed_selectors:
  GEO_long:
    label: "Country"
    selected: "United States"

loose_selectors:  
  d2_label:
    label: "Tax type"
    selected: "Gift Tax for Children"

#define the columns of the data table widget
dt.cols:
  GEO_long: "Country"
  year: "Year"
  d2_label: "Tax type"
  prorev: "EIG Tax % Total Tax Revenue"
  revgdp: "EIG Tax % GDP"
  toprat: "Top Marginal Rate"

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  d2_label: "Tax type:"
  prorev: "EIG Tax % Total Tax Revenue:"
  revgdp: "EIG Tax % GDP:"
  toprat: "Top Marginal Rate:"

#other options
download.button: True
hide.selectors: False
listen: False
table.display: True
hide.legend: False
plot_height: 700
