#define data source
data.file: "data/taxw_us_state_long.qs"

#define plot type
gopts: "line"

axis_vars:
  x_axis:
    var: "year"
    label: "Year"
    breaks: 10
  y_axis:
    var: "value"
    label: "Value"

color:
  var: "state_name"
  label: "State"
  style: "dichromat::DarkRedtoBlue_12"
  group:
    - "state_name"
    - "d2_sector_lab"

fixed_selectors:
  state_name:
    label: "State"
    selected:
      - "California"
      - "Florida"
      - "New York"
      - "Texas"
      - "Washington"
    multiple: true
  d4_concept_lab:
    label: "Tax Feature"
    selected: "Total Revenue from Tax as % of Total Tax Revenue"
    choices:
      - "Total Revenue from Tax"
      - "Total Revenue from Tax as % of Total Tax Revenue"
  xrate_lab:
    label: "Currency"
    hidden: True
    selected: "USD (2023 prices)"
    choices:
      - "USD (2023 prices)"
  show_zero:
    label: "Show Zero"
    hidden: True
    selected: "No"
    choices:
      - "Yes"
      - "No"

loose_selectors:
  d2_sector_lab:
    label: "Tax type"
    type: "very reactive checkbox"
    selected:
      - "EIG Tax, general government level"

dt.cols:
  state_name: "State"
  GEO: "State code"
  year: "Year"
  d4_concept_lab: "Variable"
  d2_sector_lab: "Type of tax"
  value: "Value"

tooltip_vars:
  state_name: "State:"
  year: "Year:"
  value: "Value:"
  d4_concept_lab: "Tax feature:"
  d2_sector_lab: "Type of tax:"

download.button: True
hide.selectors: False
listen: False
table.display: True
hide.legend: False
plot_height: 700
