#define data source
data.file: "data/ineq_warehouse_meta_v1_2.csv"
meta.file: "data/methodological_table.xlsx"
meta.loc: "tab"
data.wrangler: "custom_code/dictionary_loader_ineq.R"

#combine columns into a string variable if needed 
new.cols: 
  var_per:
    - "d3_vartype_lab"
    - "percentile"

#define plot type 
gopts: 
 - "line"
 - "point"
plot_height: 700
hide.selectors: False
hide.legend: False
download.button: True
listen: False
 
#define main plot variables 
axis_vars: 
  x_axis:
    var: "year"
    label: "Year"
    breaks: 10 
  y_axis:   
    var: "value" 
    label: "Value"
    
color:     
  var: "legend"
  label: "Source"
  style: "LaCroixColoR::CranRaspberry"

#Define main selectors 
fixed_selectors:
  GEO_long:
    label: "Country"
    selected:
      - "United States"
  var_per:
     label: "Variable"
     selected: "Share of Total Net Wealth, p99p100"
  d5_dboard_specific_lab:
    label: "Unit of analysis"
    selected:
      - "Individuals - Adults"
      - "Individuals - Adults (equal split)"
      - "Households"
      - "Tax Units"
    multiple: true 

#Define reactive or 'loose' selectors (react to changes in main selectors)
loose_selectors:
  Data_Type:
    label: "Data type"
    type: "checkbox"
  legend:
    label: "Source"
    type: "checkbox"

#define the columns of the data table widget 
dt.cols:
  GEO: "Country code"
  year: "Year"
  GEO_long: "Country"
  var_per: "Variable"
  d5_dboard_specific_lab: "Unit of Analysis"
  value: "Value"
  legend: "Source"
  metadata: "Description"
  data_description: "Metadata"
  Data_Type: "Data type"
table.display: True  

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  value: "Value:"
  legend: "Source:"
  metadata: "Explanation:"
  data_description: "Data type:"



