#define data source
data.file: "data/inhe_warehouse_meta_v2.csv"
data.wrangler: "custom_code/dictionary_loader_inhe.R"

#define plot type 
gopts: 
 - "line"
 - "point"
plot_height: 700
hide.selectors: False
hide.legend: False
download.button: True
listen: False

#combine columns into a string variable if needed 
new.cols: 
  cou_sou_val:
    - "GEO_long"
    - "legend"
    
#define main plot variables 
axis_vars: 
  x_axis:
    var: "year"
    label: "Year"
    breaks: 10 
  y_axis:   
    var: "value" 
    label: "Value"
    
color:     
  var: "cou_sou_val"
  label: "Source"
  style: "LaCroixColoR::CranRaspberry"

#Define main selectors 
fixed_selectors:
  GEO_long:
    label: "Country"
    selected:
      - "United Kingdom"
      - "France" 
      - "Italy"
      - "Switzerland"
    multiple: true
  d4_concept_lab:
    label: "Concept" 
    selected: "Inheritances & Gifts"      
  d3_vartype_lab:
     label: "Variable"
     selected: "Ratio"       
  d5_dboard_specific_lab:
    label: "Valutation"
    type: "Economic Flow"   

#define loose selectors 
loose_selectors:
   legend: 
    label: "Source"
    type: "checkbox" 
   
      

#define the columns of the data table widget 
dt.cols:
  GEO: "Country code"
  year: "Year"
  GEO_long: "Country"
  value: "Value"
  d4_concept_lab: "Concept"
  d5_dboard_specific_lab: "Valuation"
  legend: "Source"
  
table.display: True  

#define the information shown in the tooltip
tooltip_vars:
  GEO_long: "Country:"
  year: "Year:"
  value: "Value:"
  legend: "Source"
  d4_concept_lab: "Concept"
  d5_dboard_specific_lab: "Valuation" 
  



